# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03a233065b2afb456352a3855a128ac8f201111a404bbbbafefe730e3579be9248b71c6449732f7ba098bcc75b7a4671b30064536a5cd3d4f97d4302e1cb1112

test:
  secret_key_base: 5e9b3a279ec2ff023331c417f86fa690645fea2f5ee7e239bc054547b39f4a270a3b64f42099170f6d7094edf04fc1b6df9d7ff1010dd7ffd85a77c7785e1a7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
